controller_frequency: 5.0
recovery_behaviour_enabled: true

DWAPlannerROS:
  # Robot configuration parameters  
  acc_lim_x: 2.5
  acc_lim_y: 0
  acc_lim_th: 3.2

  max_vel_x: 0.5
  min_vel_x: 0.0
  max_vel_y: 0
  min_vel_y: 0

  max_trans_vel: 0.5
  min_trans_vel: 0.1
  max_rot_vel: 1.0
  min_rot_vel: 0.2

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.2
  latch_xy_goal_tolerance: false


TebLocalPlannerROS:

  odom_topic: odometry/filtered
    
 # Trajectory
  
  teb_autosize: True
  dt_ref: 0.5    #
  dt_hysteresis: 0.1
  max_samples: 500
  global_plan_overwrite_orientation: True
  allow_init_with_backwards_motion: False   #False -- che do di lui
  max_global_plan_lookahead_dist: 3.5   
  global_plan_viapoint_sep: 0.1  
  global_plan_prune_distance: 1
  exact_arc_length: True # False -- vao cua chinh xac theo cung
  feasibility_check_no_poses: 20   
  publish_feedback: False
    
 # Robot
          
  max_vel_x: 0.5
  max_vel_x_backwards: 0.0
  max_vel_y: 0.0
  max_vel_theta: 1.0

  acc_lim_x:  2.5
  acc_lim_theta: 3.2
  min_turning_radius: 0 # diff-drive robot (can turn on place!) default: 0.0

  footprint_model:
    type: "line"
    line_start: [-0.25, 0]
    line_end: [0.25, 0]

 # GoalTolerance   
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.1
  free_goal_vel: False
  complete_global_plan: True
    
 # Obstacles 
  min_obstacle_dist: 0.8  # This value must also include our robot radius, since footprint_model is set to "point".
  inflation_dist: 0.8   
  include_costmap_obstacles: True
  costmap_obstacles_behind_robot_dist: 3.0   
  obstacle_poses_affected: 5   

  dynamic_obstacle_inflation_dist: 0.6
  include_dynamic_obstacles: True    

  costmap_converter_plugin: ""
  costmap_converter_spin_thread: True
  costmap_converter_rate: 5

 # Optimization
  no_inner_iterations: 5  
  no_outer_iterations: 4   
  optimization_activate: True
  optimization_verbose: False
  penalty_epsilon: 0.1
  obstacle_cost_exponent: 2.5 
  weight_max_vel_x: 1
  weight_max_vel_theta: 1
  weight_acc_lim_x: 1   
  weight_acc_lim_theta: 1      
  weight_kinematics_nh: 500
  weight_kinematics_forward_drive: 500
  weight_kinematics_turning_radius: 500
  weight_optimaltime: 10   # must be > 0  
  weight_shortest_path: 10
  weight_obstacle: 10  
  weight_inflation: 30
  weight_dynamic_obstacle: 30   
  weight_dynamic_obstacle_inflation: 30
  weight_viapoint: 40     
  weight_adapt_factor: 2

 # Homotopy Class Planner
  enable_homotopy_class_planning: False   # True
  enable_multithreading: True
  max_number_classes: 2.0      
  selection_cost_hysteresis: 1.0
  selection_prefer_initial_plan: 0.9
  selection_obst_cost_scale: 2.0     #100
  selection_alternative_time_cost: False
 
  roadmap_graph_no_samples: 15
  roadmap_graph_area_wi2.5ation_best_duration: 3.0
  visualize_hc_graph: False
  visualize_with_time_as_z_axis_scale: False

# Recovery
  shrink_horizon_backup: True
  shrink_horizon_min_duration: 10
  oscillation_recovery: True
  oscillation_v_eps: 10
  oscillation_omega_eps: 10
  oscillation_recovery_min_duration: 10
  oscillation_filter_duration: 10
